version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py run -h 0.0.0.0 -p 5000
    container_name: web
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=infrastructure.framework.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@pentest-db:5432/pentest_db
      - SECRET_KEY='MY SECRET'
    depends_on:
      - pentest-db
    links:
      - pentest-db

  pentest-db:
    container_name: pentest-db
    build:
      context: ./infrastructure/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PROFILE=postgres
      - POSTGRES_PASSWORD=postgres
