"""empty message

Revision ID: 480e2ceecde3
Revises: bbdb03fd18be
Create Date: 2022-08-30 14:59:12.293045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480e2ceecde3'
down_revision = 'bbdb03fd18be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Vulnerability_website_id'), 'Vulnerability', ['website_id'], unique=False)
    op.create_index(op.f('ix_anomalies_website_id'), 'anomalies', ['website_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomalies_website_id'), table_name='anomalies')
    op.drop_index(op.f('ix_Vulnerability_website_id'), table_name='Vulnerability')
    # ### end Alembic commands ###
