"""empty message

Revision ID: b2c47eac200e
Revises: 
Create Date: 2022-08-29 16:16:53.438185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2c47eac200e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=254), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Vulnerability',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('website_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('attack_name', sa.String(length=254), nullable=False),
    sa.Column('num_vulnerability', sa.Integer(), nullable=True),
    sa.Column('attack_details', sa.JSON(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_id')
    )
    op.create_table('anomalies',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('website_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=254), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anomalies')
    op.drop_table('Vulnerability')
    op.drop_table('website')
    # ### end Alembic commands ###
